apiVersion: v1
kind: Service
metadata:
 name: api 
 labels:
  app: draft
  role: master
  tier: api
spec:
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 8080
 selector:
  app: draft
  tier: api
---
apiVersion: v1
kind: ReplicationController
metadata:
 name: api
 labels:
  app: draft
  tier: api
spec:
 replicas: 1
 template:
  metadata:
   labels:
    app: draft
    tier: api
  spec:
   containers:
   - name: go-api
     image: eu.gcr.io/happypoc-184207/draftapi:latest
     resources:
      requests:
       cpu: 100m
       memory: 100Mi
     env:
     - name: GET_HOSTS_FROM
       value: dns
     ports:
     - containerPort: 80

